version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: ./.docker/dev/Dockerfile
    restart: unless-stopped
    container_name: web
    volumes:
      - "./web:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/   && npm run dev"
    environment:
      - SERVER_URI=http://server:5001
    depends_on:
      - server
    networks:
      - organicmind-network

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: server
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    ports:
      - 5001:5001
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/   && npm start"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoApp
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    networks:
      - organicmind-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - organicmind-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - organicmind-network

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@todoApp.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 8080:8080 # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik-certificates:/letsencrypt"
    networks:
      - organicmind-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - organicmind-network

networks:
  organicmind-network:
    driver: bridge

volumes:
  mongo-data:
  traefik-certificates:
